server:
  port: 9191

spring: 
  application:
   name: API-GATEWAY  

  cloud:
   gateway:
    discovery:
      locator:
       enabled:true
       
    routes:
     - id: DEPARTMENT-SERVICE
       uri: lb://DEPARTMENT-SERVICE/
       predicates:
        - Path=/departments/**
          
     - id: USER-SERVICE
       uri: lb://USER-SERVICE/
       predicates:
        - Path=/users/**  
        
     - id: currency-exchange-service
       uri: lb://currency-exchange-service/
       predicates:
        - Path=/currency-exchange/**
     
     - id: currency-conversion-service
       uri: lb://currency-conversion-service/
       predicates:
        - Path=/currency-conversion/**       
     
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  
  
  instance: 
    hostname: localhost     
       