spring: 
   application:
     name: currency-conversion-service 

   config:
     import: optional:configserver:http://localhost:8888/

server:
 port: 8002     

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
      
management:
   health: 
    circuitbreakers:
      enabled: true
   endpoints:
    web:
     exposure:
      include: '*'
   endpoint:
    health:
      show-details: always
      
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.lang.RuntimeException
            
        shared:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 30
            waitDurationInOpenState: 1s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            
    instances:
        currency-exchange-service:
            baseConfig: default
     
            
resilience4j.retry:
    configs:
        default:
            maxAttempts: 3
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.lang.RuntimeException
            
    instances:
        currency-exchange-service:
            baseConfig: default
       
            
resilience4j.bulkhead:
    configs:
        default:
            maxConcurrentCalls: 100
    instances:
        currency-exchange-service:
            maxConcurrentCalls: 10
        

resilience4j.thread-pool-bulkhead:
    configs:
        default:
            maxThreadPoolSize: 4
            coreThreadPoolSize: 2
            queueCapacity: 2
    instances:
        currency-exchange-service:
            baseConfig: default
       

resilience4j.ratelimiter:
    configs:
        default:
            registerHealthIndicator: true
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            eventConsumerBufferSize: 100
    instances:
        currency-exchange-service:
            baseConfig: default
     

resilience4j.timelimiter:
    configs:
        default:
            cancelRunningFuture: true
            timeoutDuration: 2s
    instances:
        currency-exchange-service:
            baseConfig: default
        
      
